services:
  postgres:
    image: postgres:16
    container_name: pg_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
      TZ: America/Bogota
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  loader:
    image: python:3.11-slim
    container_name: xlsx_loader
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /work
    volumes:
      - ./loader:/work/loader
      - ./data:/work/data
    # No envs: instalamos deps y ejecutamos el script
    command: >
      sh -c "
        pip install --no-cache-dir pandas sqlalchemy psycopg[binary] &&
        python loader/load_from_xlsx.py
      "
volumes:
  pgdata: